from pathlib import Path

ROOT = Path.cwd()
SOURCE_PATH = f"{ROOT}/src"

SWARM_DATA_PATH = f"{SOURCE_PATH}/resources/swarmBehaviour/Swarm_Behaviour.csv"
EXPERIMENT_SCRIPTS_FOLDER = "experiments"
LOGS_PATH = f"{SOURCE_PATH}/{EXPERIMENT_SCRIPTS_FOLDER}/logs/"
MNIST_EXPERIMENT_PATH = f"{SOURCE_PATH}/{EXPERIMENT_SCRIPTS_FOLDER}/mnist/"
SYNTHETIC_EXPERIMENT_PATH = f"{SOURCE_PATH}/{EXPERIMENT_SCRIPTS_FOLDER}/synthetic/"
SWARM_EXPERIMENT_PATH = f"{SOURCE_PATH}/{EXPERIMENT_SCRIPTS_FOLDER}/swarmBehaviour/"
PLOTS_EXPERIMENT_PATH = f"{SOURCE_PATH}/{EXPERIMENT_SCRIPTS_FOLDER}/plots/"
