GLOVE_DATA_BASE_PATH = "resources/gloveData/"
GLOVE_EXPERIMENT_PATH = "experiments/glove/"
MNIST_EXPERIMENT_PATH = "experiments/mnist/"
SYNTHETIC_EXPERIMENT_PATH = "experiments/synthetic/"
SWARM_EXPERIMENT_PATH = "experiments/swarmBehaviour/"
SWARM_DATA_PATH = "resources/swarmBehaviour/Swarm_Behaviour.csv"
PLOTS_EXPERIMENT_PATH = "experiments/plots/"
